---
- name: Configure Nginx with SSL support
  hosts: all
  sudo: no
  #define some variables for the SSL information
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/conf.d/default.conf
    server_name: localhost
  tasks:
    - name: Install Nginx
      yum: name=nginx state=latest
    - name: Create the directories for SSL certs
      file: path=/etc/nginx/ssl state=directory
    - name: Copy the SSL key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx
    - name: Copy the SSL cert
      copy: src=files/nginx.crt dest={{ cert_file }} 
      notify: restart nginx
    - name: Copy config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }} 
      notify: restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=started
  
