---
- name: Configuration of Nginx - Standard setup
  hosts: all
  sudo: no
  tasks:
    - name: install nginx
      yum: name=nginx state=latest
    - name: Copy Nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/conf.d/ansible.conf
    - name: Copy Index.html
      copy: src=files/index.html dest=/var/html/index.html mode=0644
    - name: Start Nginx
      service: name=nginx state=restarted
